#!/bin/bash
# Author: Romain Ouabdelkader

if [ ! -d src ]
then
    echo "Cannot find config source"
    exit 1
fi

install_files=$(ls src/*/install 2> /dev/null)
if [ "$install_files" == "" ]
then
    echo "Nothing to do."
    exit
fi

echo "$install_files" | while read line
do
    module=$(echo "$line" | cut -d"/" -f2)
    echo -n "Installing '$module'.."
    cd "$(dirname $line)"
    "./install"
    cd - > /dev/null
    echo " done"
    if [ $? -ne 0 ]
    then
	echo "Error while installing '$module'"
	exit 1
    fi
done
