#!/bin/bash
# Author: Romain Ouabdelkader

if [ ! -d src ]
then
    echo "Cannot find config source"
    exit 1
fi

install_files=$(ls $(./util/get_modules.sh "install") 2> /dev/null)
if [ "$install_files" == "" ]
then
    echo "Nothing to do."
    exit
fi

for line in $install_files
do
    module=$(echo "$line" | cut -d"/" -f2)
    echo "Installing '$module'.."
    cd "$(dirname $line)"
    "./install"
    if [ $? -ne 0 ]
    then
	echo "Error while installing '$module'"
	exit 1
    fi
    cd - > /dev/null
done

echo "Compiling emacs config.."
util/compile.sh
./remote-module setup

if [ $? -eq 0 ]
then
    echo
    echo
    echo "---------------------------------------------------"
    echo "Done"
    echo "If you want to modify which modules you want to use. Please modify src/custom-modules.el. (visit src/default-modules.el for more infos)"
    echo "You can now add the following lines to your .emacs:"
    echo
    echo "(let ((config \"$(pwd)/src/init.el\"))"
    echo "  (if (file-exists-p config)"
    echo "      (load-file config)))"
fi
