;; Load all conf modules

(conf:load-module "themes")
(conf:load-module "emacs-settings")
(conf:load-module "gui")

(conf:load-module "auto-complete")
(conf:load-module "auto-complete-clang-async")
(conf:load-module "autopair")
(conf:load-module "basic-keybindings")
(conf:load-module "duplicate-region")
(conf:load-module "git-gutter-fringe")
(conf:load-module "highlight-symbol")
(conf:load-module "ido")
(conf:load-module "multiple-cursors")
(conf:load-module "powerline")
(conf:load-module "smooth-scroll")
(conf:load-module "tags")
(conf:load-module "undo-tree")
(conf:load-module "window")
(conf:load-module "yasnippet")
